package claude

import (
	"testing"

	"herdr-tree/internal/adapter"
)

func kinds(nodes []adapter.Node) (ids []string, kinds []adapter.Kind, titles []string) {
	for _, n := range nodes {
		ids = append(ids, n.ID)
		kinds = append(kinds, n.Kind)
		titles = append(titles, n.Title)
	}
	return
}

func TestEntriesProjectsPromptsRepliesAndToolCalls(t *testing.T) {
	es, _, err := ParseFile("testdata/simple.jsonl")
	if err != nil {
		t.Fatal(err)
	}
	got := Entries(es)
	ids, ks, titles := kinds(got)
	wantIDs := []string{"u1", "a2", "u3", "a3"}
	if len(ids) != len(wantIDs) {
		t.Fatalf("got %v want %v", ids, wantIDs)
	}
	for i := range wantIDs {
		if ids[i] != wantIDs[i] {
			t.Fatalf("got %v want %v", ids, wantIDs)
		}
	}
	wantKinds := []adapter.Kind{adapter.KindHuman, adapter.KindToolCall, adapter.KindHuman, adapter.KindAssistant}
	for i := range wantKinds {
		if ks[i] != wantKinds[i] {
			t.Fatalf("node %d kind = %v want %v", i, ks[i], wantKinds[i])
		}
	}
	if titles[1] != "[bash]" {
		t.Fatalf("tool call title = %q, want the call not the output", titles[1])
	}
}

func TestToolCallRendersTheCallNotTheOutput(t *testing.T) {
	lines := []string{
		`{"type":"user","uuid":"u1","parentUuid":null,"sessionId":"S","message":{"role":"user","content":[{"type":"text","text":"read a file"}]}}`,
		`{"type":"assistant","uuid":"a1","parentUuid":"u1","sessionId":"S","requestId":"r1","message":{"role":"assistant","content":[{"type":"tool_use","id":"t1","name":"Read","input":{"file_path":"/home/x/notes.txt"}}]}}`,
		`{"type":"user","uuid":"tr1","parentUuid":"a1","sessionId":"S","toolUseResult":{"ok":true},"message":{"role":"user","content":[{"type":"tool_result","tool_use_id":"t1"}]}}`,
	}
	var es []Entry
	for _, l := range lines {
		e, err := parseLine([]byte(l))
		if err != nil {
			t.Fatal(err)
		}
		es = append(es, e)
	}
	got := Entries(es)
	if len(got) != 2 {
		t.Fatalf("got %d nodes want 2 (prompt + call, never the result)", len(got))
	}
	if got[1].Title != "[read: /home/x/notes.txt]" {
		t.Fatalf("tool call title = %q", got[1].Title)
	}
}

func TestPeerMessageNeverBecomesANode(t *testing.T) {
	es, _, err := ParseFile("testdata/origin.jsonl")
	if err != nil {
		t.Fatal(err)
	}
	got := Entries(es)
	for _, n := range got {
		if n.ID == "peer1" {
			t.Fatalf("a peer message must never become a node: %+v", n)
		}
	}
}

func TestOriginKindHumanIsPreferredOverHeuristics(t *testing.T) {
	// o2's text looks like injected bash-input scaffolding, which the
	// heuristic fallback would drop. Its origin.kind is "human" and the
	// transcript records origin at all, so the authoritative path must win.
	es, _, err := ParseFile("testdata/origin.jsonl")
	if err != nil {
		t.Fatal(err)
	}
	got := Entries(es)
	found := false
	for _, n := range got {
		if n.ID == "o2" {
			found = true
		}
		if n.ID == "skill1" {
			t.Fatalf("skill1 has no origin.kind:human, so it must be dropped even though the transcript has origin: %+v", n)
		}
	}
	if !found {
		t.Fatal("o2 has origin.kind human and must be kept despite its bash-input-shaped text")
	}
}

func TestTranscriptWithNoOriginAtAllStillYieldsPrompts(t *testing.T) {
	es, _, err := ParseFile("testdata/simple.jsonl")
	if err != nil {
		t.Fatal(err)
	}
	if HasHumanOrigin(es) {
		t.Fatal("fixture setup: simple.jsonl must not carry origin")
	}
	got := Entries(es)
	var humanCount int
	for _, n := range got {
		if n.Kind == adapter.KindHuman {
			humanCount++
		}
	}
	if humanCount != 2 {
		t.Fatalf("got %d human prompts want 2", humanCount)
	}
}

func TestEntriesExcludesSlashCommandMachineryButSelectKeepsIt(t *testing.T) {
	// Claude Code writes a caveat banner, the command name and its captured
	// stdout as user entries around every slash command. They are real
	// transcript content — Select keeps them — but they are not turns anyone
	// would branch from, and they crowd the top of almost every session.
	lines := []string{
		`{"type":"user","uuid":"m1","parentUuid":null,"sessionId":"S","message":{"role":"user","content":[{"type":"text","text":"<local-command-caveat>Caveat: the messages below were generated by the user</local-command-caveat>"}]}}`,
		`{"type":"user","uuid":"m2","parentUuid":"m1","sessionId":"S","message":{"role":"user","content":[{"type":"text","text":"<command-name>/model</command-name>"}]}}`,
		`{"type":"user","uuid":"m3","parentUuid":"m2","sessionId":"S","message":{"role":"user","content":[{"type":"text","text":"<local-command-stdout>Set model to opus</local-command-stdout>"}]}}`,
		`{"type":"user","uuid":"m4","parentUuid":"m3","sessionId":"S","message":{"role":"user","content":[{"type":"text","text":"a real question"}]}}`,
	}
	var es []Entry
	for _, l := range lines {
		e, err := parseLine([]byte(l))
		if err != nil {
			t.Fatal(err)
		}
		es = append(es, e)
	}
	got := Entries(es)
	if len(got) != 1 || got[0].ID != "m4" {
		var ids []string
		for _, n := range got {
			ids = append(ids, n.ID)
		}
		t.Fatalf("got %v want only [m4]", ids)
	}
	keep, err := Select(es, "m4")
	if err != nil {
		t.Fatal(err)
	}
	for _, u := range []string{"m1", "m2", "m3"} {
		if !keep[u] {
			t.Fatalf("Select dropped %s; hiding a row from the tree must not delete it from the transcript", u)
		}
	}
}

func TestClassifyDropsTextlessAssistantAndThinking(t *testing.T) {
	lines := []string{
		`{"type":"assistant","uuid":"a1","parentUuid":null,"sessionId":"S","message":{"role":"assistant","content":[{"type":"thinking","thinking":"hmm"}]}}`,
		`{"type":"assistant","uuid":"a2","parentUuid":"a1","sessionId":"S","message":{"role":"assistant","content":[{"type":"text","text":"   "}]}}`,
	}
	for _, l := range lines {
		e, err := parseLine([]byte(l))
		if err != nil {
			t.Fatal(err)
		}
		if _, keep := Classify(e, false); keep {
			t.Fatalf("entry %v should have been dropped", e.UUID())
		}
	}
}

func TestTurnTitleIsFirstLineTruncated(t *testing.T) {
	es, _, _ := ParseFile("testdata/simple.jsonl")
	got := Entries(es)
	if got[2].Title != "second question" {
		t.Fatalf("got %q", got[2].Title)
	}
}
