package claude

import "testing"

func TestTurnsFiltersNonPrompts(t *testing.T) {
	es, _, err := ParseFile("testdata/simple.jsonl")
	if err != nil {
		t.Fatal(err)
	}
	got := Turns(es)
	var ids []string
	for _, n := range got {
		ids = append(ids, n.ID)
	}
	want := []string{"u1", "u3"}
	if len(ids) != len(want) {
		t.Fatalf("got %v want %v", ids, want)
	}
	for i := range want {
		if ids[i] != want[i] {
			t.Fatalf("got %v want %v", ids, want)
		}
	}
}

func TestTurnsExcludeSlashCommandMachinery(t *testing.T) {
	// Claude Code writes a caveat banner, the command name and its captured
	// stdout as user entries around every slash command. They are real
	// transcript content — Select keeps them — but they are not turns anyone
	// would branch from, and they were the first three rows of most sessions.
	lines := []string{
		`{"type":"user","uuid":"m1","parentUuid":null,"sessionId":"S","message":{"role":"user","content":[{"type":"text","text":"<local-command-caveat>Caveat: the messages below were generated by the user</local-command-caveat>"}]}}`,
		`{"type":"user","uuid":"m2","parentUuid":"m1","sessionId":"S","message":{"role":"user","content":[{"type":"text","text":"<command-name>/model</command-name>"}]}}`,
		`{"type":"user","uuid":"m3","parentUuid":"m2","sessionId":"S","message":{"role":"user","content":[{"type":"text","text":"<local-command-stdout>Set model to opus</local-command-stdout>"}]}}`,
		`{"type":"user","uuid":"m4","parentUuid":"m3","sessionId":"S","message":{"role":"user","content":[{"type":"text","text":"a real question"}]}}`,
	}
	var es []Entry
	for _, l := range lines {
		e, err := parseLine([]byte(l))
		if err != nil {
			t.Fatal(err)
		}
		es = append(es, e)
	}
	got := Turns(es)
	if len(got) != 1 || got[0].ID != "m4" {
		var ids []string
		for _, n := range got {
			ids = append(ids, n.ID)
		}
		t.Fatalf("got %v want only [m4]", ids)
	}
	// but grafting must still carry them: they are transcript content
	keep, err := Select(es, "m4")
	if err != nil {
		t.Fatal(err)
	}
	for _, u := range []string{"m1", "m2", "m3"} {
		if !keep[u] {
			t.Fatalf("Select dropped %s; hiding a row from the tree must not delete it from the transcript", u)
		}
	}
}

func TestTurnTitleIsFirstLineTruncated(t *testing.T) {
	es, _, _ := ParseFile("testdata/simple.jsonl")
	got := Turns(es)
	if got[1].Title != "second question" {
		t.Fatalf("got %q", got[1].Title)
	}
}

func TestTitleTruncation(t *testing.T) {
	cases := []struct{ in, want string }{
		{"short", "short"},
		{"", ""},
		{"\n\n  leading blanks", "leading bl…"},
		{"0123456789abcdef", "0123456789…"},
	}
	for _, c := range cases {
		if got := Title(c.in, 11); got != c.want {
			t.Fatalf("Title(%q) = %q want %q", c.in, got, c.want)
		}
	}
}

func TestSessionTitlePrefersAITitle(t *testing.T) {
	es, _, _ := ParseFile("testdata/simple.jsonl")
	if got := SessionTitle(es); got != "Fixture session" {
		t.Fatalf("got %q", got)
	}
}
